### ISSUE TITLE
Addressing Recommendation Tab Display Issue

### ISSUE THREAD

**Issue by Ali-Hakan** [SWE574-G3/Living-Stories-App#147]
The number of stories displayed in the recommendation tab is currently incorrect, exceeding the maximum limit of 5. We need to rectify this issue to ensure that the recommendation tab displays a maximum of 5 stories as intended.

**Comment by JohnsL-U** [comment]
Tests conducted through rec-engine endpoint successfully returned correct number of stories computed by rec-engine.

**Comment by Ali-Hakan** [comment]
> Tests conducted through rec-engine endpoint successfully returned correct number of stories computed by rec-engine.

Nice to hear. I shall check debug further in both backend and frontend to address the issue.

**Comment by JohnsL-U** [comment]
Since the front end directly gets the list of recommended stories from recommendation-engine, I highly doubt it has to do with backend. Would be great to receive a confirmation from the backend team. In the meantime, you can use the following url to directly check the number of stories returned and compare it with stories displayed. 
*Make sure to add a user id at the end of it.

http://35.246.216.172:5002/recommendations?user_id=

**Comment by Ali-Hakan** [comment]
[Commit](https://github.com/SWE574-G3/Living-Stories-App/commit/96c21d04baf4146c902b1586f721245623e5d41a)

The problem has been successfully addressed by ensuring proper mapping alignment.
